# Generated by Django 4.1.5 on 2023-01-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_customer_order_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="price",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="total",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
